### ISSUE TITLE
Script won't work with Python 3.12

### ISSUE THREAD

**Issue by Mojiberus** [havokentity/SteamIconsFix#3]
As I tested, the dependencies installer script won't work if Python version is 3.12
![image](https://github.com/havokentity/SteamIconsFix/assets/63734948/a0d3a7da-f14c-40ba-b8e6-3c40e8900a17)
However, running this this with Python 3.11 instead goes smoothly as intended
![image](https://github.com/havokentity/SteamIconsFix/assets/63734948/5d4f998f-2995-4921-86fe-9c0cfd1058c7)
Therefore, either script needs to be updated to work with 3.12 and higher without installing MS Visual C++ 14.0 or mention that it currently only works with Python 3.11

**Comment by havokentity** [comment]
@Mojiberus  I have Python 3.12 locally and seems to run fine. Will test on a fresh Windows VM this weekend and see if it's possibly a MSVC build tools dependency with 3.12

**Comment by XHead-git** [comment]
I've removed the line "cffi==1.15.1" from the requirements.txt, and it worked great with Python 3.12

**Comment by havokentity** [comment]
@XHead-git Thanks for that, I'll incorporate the changes this weekend after testing. I completely forgot that this issue was open.
